import streamlit as st
from pathlib import Path
from PIL import Image
import subprocess

st.set_page_config(page_title="UAV Relay Repositioning", layout="wide")

st.title("UAV Relay Repositioning Demo")
st.write("""
This app visualizes the **UAV relay repositioning** project.

- Custom Gym environment for UAV relay
- PPO training + greedy SNR baseline
- Evaluation with UAV path plots
""")

st.subheader("1️⃣ Run Evaluation and Generate UAV Path Plot")

st.write("Click the button below to run the evaluation script. It will generate a UAV path image (e.g., `uav_paths.png`).")

if st.button("Run evaluation"):
    st.info("Running `python -m eval.evaluate` ...")
    try:
        # Run your evaluation script as a module so imports like `from envs...` work
        result = subprocess.run(
            ["python", "-m", "eval.evaluate"],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            st.success("Evaluation completed successfully.")
            if result.stdout:
                st.caption("Evaluation output:")
                st.code(result.stdout)
        else:
            st.error("Evaluation script returned an error.")
            st.code(result.stderr or "No stderr captured.")
    except Exception as e:
        st.error(f"Error running evaluation: {e}")

st.subheader("2️⃣ UAV Path Visualization")

# Adjust this path to wherever your code saves the image
candidate_paths = [
    Path("uav_paths.png"),
    Path("assets/uav_paths.png"),
    Path("eval/uav_paths.png"),
]

img_path = None
for p in candidate_paths:
    if p.exists():
        img_path = p
        break

if img_path and img_path.exists():
    st.write(f"Showing UAV path from: `{img_path}`")
    image = Image.open(img_path)
    st.image(image, caption="UAV Path Generated by the Model", use_column_width=True)
else:
    st.warning("No UAV path image found yet. Run evaluation first, or check that your script saves an image file.")
